Import('env')
libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
libraries = libraries + ['dfs','dfs_helper','daos_seis', 'su', 'par', 'cwp', 'm', 'gurt']
libraries_path = ['../../build/dfs_helper_build', '../../build/client/seis_build']
libraries_path = libraries_path + ['../../build/su_build','../../build/par_build','../../build/cwp_build']
print("Calling Program('SEISMIC TESTS')")
env.Program('seismic_obj_creation', 'seismic_obj_creation.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('get_traces_count', 'get_traces_count.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('read_traces', 'read_traces.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('sort_traces', 'sort_traces.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('window_traces', 'window_traces.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('set_headers', 'set_headers.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('change_headers', 'change_headers.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('range_headers', 'range_headers.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('get_headers', 'get_headers.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('update_traces_data', 'update_traces_data.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('parse_additional_file', 'parse_additional_file.c', LIBS=libraries, LIBPATH=libraries_path)
