Import('env')
libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
libraries = libraries + ['dfs','dfs_helper','daos_seis']
libraries_path = ['../../build/dfs_helper_build', '../../build/client/seis_build']
print("Calling Program('SEISMIC TESTS')")
env.Program('seismic_obj_creation', 'seismic_obj_creation.c', LIBS=libraries, LIBPATH=libraries_path)


