Import('env')
#env = env.Clone()
env.AppendUnique(CPPPATH=['include'])
print("Calling Program('CWP')")
#libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
#libraries = libraries + ['dfs','m']
env.StaticLibrary('cwp', ['alloc.c',
	'exit.c',
	'strstuff.c',
	'swapbyte.c',
	'tempname.c'],LIBS=['m'])
