Import('env')
#env = env.Clone()
env.AppendUnique(CPPPATH=['include'])
print("Calling Program('SU')")
#libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
#libraries = libraries + ['dfs','par','cwp','m', 'dfs_helper']
env.StaticLibrary('su',['elco_scalar.c',
	'fgetgthr.c',
	'fgethdr.c',
	'fgettr.c',
	'fputgthr.c',
	'fputtr.c',
	'getSPSfield.c',
	'hdrpkge.c',
	'tabplot.c',
	'valpkge.c',
	'xdrbhdrsub.c',
	'xdrhdrsub.c'], LIBS=['par','cwp','m', 'dfs_helper'])
