Import('env')

print("Calling Program('DAOS primitives module')")
libraries = ['$LIBS', 'daos_common', 'daos', 'uuid', 'dfs']
env.SharedLibrary('daos_primitives',['dfs_helpers.c','operations_controller.c','object.c','array.c'],LIBS=libraries, variant_dir='../../build/src_build/daos_primitives')
