Import('env')
#env = env.Clone()
env.AppendUnique(CPPPATH=['include'])
print("Calling Program('PAR')")
#libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
#libraries = libraries + ['dfs','cwp','m']
env.StaticLibrary('par',['atopkge.c',
	'docpkge.c',
	'ealloc.c',
	'errpkge.c',
	'filestat.c',
	'getpars.c',
	'subcalls.c',
	'syscalls.c'],LIBS=['cwp','m'])

