Import('env')
libraries = ['$LIBS', 'daos_common', 'daos', 'uuid']
libraries = libraries + ['dfs','dfs_helper','su','par','cwp','m']
libraries_path = ['../../build/dfs_helper_build','../../build/su_build','../../build/par_build','../../build/cwp_build']
print("Calling Program('main')")
env.Program('segyread.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('suaddhead.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('sugethw.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('sushw.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('sutrcount.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('suchw.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('surange.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('suwind.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('susort.c', LIBS=libraries, LIBPATH=libraries_path)
env.Program('dfs_file_mount.c', LIBS=libraries, LIBPATH=libraries_path)


